automation:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/workflows/**"
      - ".github/labeler.yml"
      - "utils/**"
meta:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/**"
docs:
  - changed-files:
    - any-glob-to-any-file:
      - "docs/**"
      - "README.md"
tests:
  - changed-files:
    - any-glob-to-any-file:
      - "test/**"
core:
  - changed-files:
    - any-glob-to-any-file:
      - "bank2ynab/**"
plugins:
  - changed-files:
    - any-glob-to-any-file:
      - "bank2ynab/plugins/**"
config:
  - changed-files:
    - any-glob-to-any-file:
      - "bank2ynab/data/**"
      - "bank2ynab/config_handler.py"
api:
  - changed-files:
    - any-glob-to-any-file:
      - "bank2ynab/ynab_api.py"
      - "bank2ynab/api_interface.py"
packaging:
  - changed-files:
    - any-glob-to-any-file:
      - "pyproject.toml"
      - "uv.lock"
      - "LICENSE"
windows:
  - changed-files:
    - any-glob-to-any-file:
      - "bank2ynab.bat"
