changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New Features
      labels:
        - enhancement
        - bank format
    - title: Bug Fixes
      labels:
        - bug
    - title: Internal & CI
      labels:
        - CI
        - optimisation
        - meta
        - packaging
        - distribution
        - documentation
